spring.application.name=ejercicio_04

# Puerto
server.port=8080

# Configuración de H2
spring.datasource.url=jdbc:h2:mem:alumnosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar consola web en http://localhost:8080/h2-console
spring.h2.console.enabled=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

